renaming
yours-org/yours-wallet pull request #1
Opened 2024-03-07 11:15 UTC by afomi

![Screenshot 2024-03-07 at 3 15 25 AM](https://github.com/yours-org/yours-wallet/assets/67984/f2050e7d-3374-45aa-ae75-44d049c87624)

2024-03-07 17:23 UTC, danwag06 requested changes
Overall this is hugely helpful.

However, we need to make sure these changes are synced with:
https://github.com/Panda-Wallet/panda-wallet-provider

IMPORTANT: things must remain backwards compatible. If you are going to tackle the provider part too, make sure all the types are in sync. Fine with bumping the version of the provider version with a MAJOR change since it would break things. People would just need to update their types if upgrading to v3.0.0 of the provider.

In general, i'm struggling with best way to move all existing issues from the origin Panda repo and have everyone just start working from the Yours fork. Would be nice to migrate all existing issues and this project Kanban if possible https://github.com/orgs/Panda-Wallet/projects/1

Ideally the panda repo just becomes deprecated in favor of the yours repo since we are expecting all the action to move here.

2024-03-07 17:23 UTC, danwag06 commented on src/components/YoursHead.tsx
> +      alt="Yours Head"
Yours Icon

2024-03-07 17:23 UTC, danwag06 commented on src/components/YoursHead.tsx
> +      src={yoursLogo}
The source of this image should be updated to use the Yours Logo attached.
<img width="72" alt="yours-logo" src="https://github.com/yours-org/yours-wallet/assets/25462225/be240c2e-8d82-4502-82ac-423b017a3b5b">

2024-03-07 17:23 UTC, danwag06 commented on src/pages/onboarding/ImportWallet.tsx
> +import { YoursHead } from '../../components/YoursHead';
`YoursIcon`

2024-03-07 17:23 UTC, danwag06 commented on src/pages/onboarding/ImportWallet.tsx
> +        <YoursHead />
`<YoursIcon />`

2024-03-07 17:23 UTC, danwag06 commented on src/utils/constants.ts
> +export const HOSTED_YOURS_IMAGE = 'https://i.ibb.co/3fLL5X2/Panda-Wallet-Logo.png';
Update to use the yours icon attached in one of the other comments

2024-03-10 07:00 UTC, afomi commented on src/pages/onboarding/ImportWallet.tsx
> +import { YoursHead } from '../../components/YoursHead';
https://github.com/afomi/yours-wallet/commit/787a50cf04e9db58f776c2ff148acc51b46e632e

2024-03-10 07:00 UTC, afomi commented on src/pages/onboarding/ImportWallet.tsx
> +        <YoursHead />
https://github.com/afomi/yours-wallet/commit/787a50cf04e9db58f776c2ff148acc51b46e632e

2024-03-10 07:05 UTC, afomi commented on src/utils/constants.ts
> +export const HOSTED_YOURS_IMAGE = 'https://i.ibb.co/3fLL5X2/Panda-Wallet-Logo.png';
https://github.com/afomi/yours-wallet/commit/811d296114177e6caa404483e31de5f9a3f0ed12

2024-03-10 07:08 UTC, afomi commented
updates made to address the comments,
and provider branch is a WIP at https://github.com/Panda-Wallet/panda-wallet-provider/pull/7

2024-05-07 20:12 UTC, merged