Firefox extension
yours-org/yours-wallet pull request #18
Opened 2023-10-08 15:23 UTC by jadwahab

Made some changes to the manifest.json that were causing errors when trying to submit the code to the Firefox Addons stone (AMO - addons.mozilla.org). Finally got it working and you can download the extension [here](https://addons.mozilla.org/en-US/firefox/addon/panda-wallet/). Seems like the process has to be manual and there's no way to connect the github repo or something like that. 

Apparently there is a Mozilla tool called `web-ext` that can help streamline, but we need to do this process for every new version we want to push to the AMO.

Haven't really done this browser development stuff before so I'm not 100% what the changes to the manifest.json file fully mean but it was just a process of trial and error to get it working. Didn't break things for me on the Chrome side but would be great if someone else could make sure before it's merged.

2023-10-08 15:25 UTC, jadwahab commented
Doesn't seem like I'm able to link this PR to issue #15, might need to be done by an admin.

2023-10-08 17:43 UTC, danwag06 requested changes
@jadwahab There are a few things I think we need to address. I did the following and got the attached image result in chrome.

1. Pulled down your changes
2. Checkout to the pr branch
3. Ran `npm run build`
4. Head to chrome://extensions and load unpacked build file

I know v3 of chrome ext requires the `service-worker`. Was originally using v3 (as it's the latest) but if we need to use a prior version for it to work then we can use that instead (v3 would be preferred though if we can get it to work). @ZacharyWeiner mentioned something about this in a call recently.

The main thing is that it should build in both chrome and firefox and make sure that the provider functionality still works. You should be able to open the browser console and call `window.panda.connect()` and have it launch the wallet in a mini window (test in chrome and firefox).

<img width="507" alt="Screen Shot 2023-10-08 at 10 37 56 AM" src="https://github.com/Panda-Wallet/panda-wallet/assets/25462225/ec56470d-e416-4314-8edc-eda14871caaf">

2023-10-08 17:43 UTC, danwag06 commented on public/manifest.json
> +  "permissions": ["storage", "activeTab", "tabs"],
I assume removing `windows` will break the "provider" functionality (I believe it relies on it for the popup windows).

2023-10-08 17:43 UTC, danwag06 commented on public/manifest.json
> +      "id": "panda-wallet-bsv@example.com"
What would this ideally be instead of "@example.com"? Should we register a domain for the project?

2023-11-05 05:25 UTC, danwag06 commented
@jadwahab I'm going to close this for now until you want to pick it back up... A lot has changed since this was opened.

2023-11-05 05:25 UTC, closed without merging