Added QR Code Export for Wallet: Simplify wallet import for mobile apps
yours-org/yours-wallet pull request #62
Opened 2023-10-27 03:23 UTC by arrorLabArts

**QR Code Wallet Export:** Users can now export their Panda Wallets (payment pk,ord pk, wallet seeds, derivation paths) as a QR code.
**Streamlined Mobile App Imports:** Third-party mobile apps can swiftly import Panda Wallets using QR codes, ensuring a seamless user experience.
**Security:** This commit also includes code that automatically removes the QR code after 10 seconds as a simple security measure.

This improvement should further increase the versatility and interoperability of Panda Wallet

2023-10-27 08:12 UTC, danwag06 requested changes
@arrorLabArts This looks good. 

One small request. I think It would be nice to consolidate the two `Export Keys` options into one and then let the user drill in. Follow the same pattern as `Connected Apps` with the arrow. (Just to keep it from getting two crowded)

1. Make the current Export Keys description a little more generic to account for both options and show arrow indicating the user can drill in
2. When the user drills in have the top header change from "Settings" to "Export Keys"
3. Use the existing `<SettingsRow>` components on the new page and call it day.

2023-10-28 02:23 UTC, arrorLabArts commented
I've made a few updates; please let me know if any further improvements are needed.

2023-10-28 21:49 UTC, danwag06 requested changes
After these changes we can get it merged. Nice work!

2023-10-28 21:49 UTC, danwag06 commented on src/pages/Settings.tsx
> +          jsxElement={<ForwardButton />}
Remove the forward button here

2023-10-28 21:49 UTC, danwag06 commented on src/pages/Settings.tsx
> +      <SettingsRow
Put a wrapper around this or use some other means to bring the items towards the top rather than the center of the screen.

2023-10-28 21:49 UTC, danwag06 commented on src/pages/Settings.tsx
> +          description="Show your keys (private,public & seed) as QR code for wallets to scan & import"
"Display private keys as QR code for mobile import"

or something similar. I'd like to see this on a single line without wrapping

2023-10-29 18:24 UTC, danwag06 commented
Update: I'm going to go ahead and get this merged due to another PR that will likely create some conflicts. I'll handle the remaining suggestions. Thanks!

2023-10-29 18:24 UTC, danwag06 approved these changes

2023-10-29 18:24 UTC, merged

2023-10-30 04:31 UTC, arrorLabArts commented
sounds good. Thanks